### PR TITLE
Break syntax to allow PurgeCSS compatibility

### PR DESCRIPTION
**Pull request by cies**
New versions of Tailwind are so big they go hand-in-hand with PurgeCSS, which requires the CSS names to be verbatim in the JS output. This breaks with the responsive variant functions (`sm`, `md`, etc.). Hence they've been replaced with a `sm__px_3` syntaxt.

It works now with PurgeCSS, but the generated Elm files is huge.

Not sure how to fix this otherwise: a clean/sensible solution to kinda type safe Tailwind in Elm seems to be rather hard.

### CODE REVIEW

**Comment by cies** [comment]
I can supply a starter/example project that uses webpack+purgecss together with a small Elm project, showing how this would work in a production-able setup.

**Comment by cies** [comment]
no hard feelings if you do not want to merge this, but then I will fork. really, really, really, no problem at all for me. im a firm believer in open source and collaboration, hence i try to feed my work back into the original project. but i see there can be many reasons it simply does not work out.

**Comment by cies** [comment]
@afidegnum No response on the PRs. Again, no hard feelings at all, but this means I'm probably forking when I find the time.

**Comment by afidegnum** [comment]
@cies  HI, sorry for the late reply, i have been away for a long period of time. i'm back on track now. Thanks for your immense contribution, I will be merging your commits

**Comment by cies** [comment]
No worries. Do you intend to push it to https://package.elm-lang.org ?

**Pull request merged**
